coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%  # Allow defensive code paths
        threshold: 5%

ignore:
  - "**/*_test.go"
